---
- hosts: servers
  tasks:
    - name: Pull the latest Docker image
      command: docker pull your-dockerhub-username/my-flask-app:latest

    - name: Stop the running container (if any)
      command: docker stop flask-app
      ignore_errors: yes

    - name: Remove the old container (if any)
      command: docker rm flask-app
      ignore_errors: yes

    - name: Run the new container
      command: docker run -d --name flask-app -p 5000:5000 your-dockerhub-username/my-flask-app:latest
